### ISSUE TITLE
Add graph from Willis' thesis, p.37, fig.5.7

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#48] opened 2017-05-25 15:30 UTC
please add some description (from the caption)

**Comment by harrisbm3** [comment] 2017-05-26 14:38
Ill do this one

**Comment by harrisbm3** [comment] 2017-05-26 14:53
A graph where non of the lower bounds considered here give the value for the independence number.

'GsOiho'

**Comment by rbarden** [comment] 2017-05-31 15:15
Duplicate of Fig. 2.1. Not adding and closing.

**Closed by rbarden** 2017-05-31 15:15 UTC
